name: jaspr_declarative_tailwind
description: A declarative tailwind generator for dart.
version: 0.1.0
homepage: https://github.com/cybertheory/jaspr-declarative-tailwind
issue_tracker: https://github.com/cybertheory/jaspr-declarative-tailwind/issues
documentation: https://docs.page/schultek/jaspr
funding:
  - https://github.com/sponsors/schultek

topics:
  - jaspr
  - web
  - html
  - css

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.0.0
  build_modules: ^5.0.4
  glob: ^2.1.2
  jaspr: ^0.3.0
  path: ^1.8.3
  quiver: ^3.2.1
  test: ^1.25.0

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_tailwind: ^0.1.0
  lints: ^2.1.0
